/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UseGenRouteImport } from './routes/use-gen'
import { Route as PromptEditorRouteImport } from './routes/prompt-editor'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AgentEditorRouteImport } from './routes/agent-editor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiChatsIndexRouteImport } from './routes/api/chats/index'
import { Route as ApiChatsChatIdRouteImport } from './routes/api/chats/$chatId'
import { Route as ApiAgentEditorChatIdRouteImport } from './routes/api/agent-editor/$chatId'
import { Route as ApiChatsChatIdMessagesMessageIdRouteImport } from './routes/api/chats/$chatId/messages/$messageId'

const UseGenRoute = UseGenRouteImport.update({
  id: '/use-gen',
  path: '/use-gen',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptEditorRoute = PromptEditorRouteImport.update({
  id: '/prompt-editor',
  path: '/prompt-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentEditorRoute = AgentEditorRouteImport.update({
  id: '/agent-editor',
  path: '/agent-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatsIndexRoute = ApiChatsIndexRouteImport.update({
  id: '/api/chats/',
  path: '/api/chats/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatsChatIdRoute = ApiChatsChatIdRouteImport.update({
  id: '/api/chats/$chatId',
  path: '/api/chats/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentEditorChatIdRoute = ApiAgentEditorChatIdRouteImport.update({
  id: '/api/agent-editor/$chatId',
  path: '/api/agent-editor/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatsChatIdMessagesMessageIdRoute =
  ApiChatsChatIdMessagesMessageIdRouteImport.update({
    id: '/messages/$messageId',
    path: '/messages/$messageId',
    getParentRoute: () => ApiChatsChatIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-editor': typeof AgentEditorRoute
  '/chat': typeof ChatRoute
  '/prompt-editor': typeof PromptEditorRoute
  '/use-gen': typeof UseGenRoute
  '/api/chat': typeof ApiChatRoute
  '/api/agent-editor/$chatId': typeof ApiAgentEditorChatIdRoute
  '/api/chats/$chatId': typeof ApiChatsChatIdRouteWithChildren
  '/api/chats/': typeof ApiChatsIndexRoute
  '/api/chats/$chatId/messages/$messageId': typeof ApiChatsChatIdMessagesMessageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-editor': typeof AgentEditorRoute
  '/chat': typeof ChatRoute
  '/prompt-editor': typeof PromptEditorRoute
  '/use-gen': typeof UseGenRoute
  '/api/chat': typeof ApiChatRoute
  '/api/agent-editor/$chatId': typeof ApiAgentEditorChatIdRoute
  '/api/chats/$chatId': typeof ApiChatsChatIdRouteWithChildren
  '/api/chats': typeof ApiChatsIndexRoute
  '/api/chats/$chatId/messages/$messageId': typeof ApiChatsChatIdMessagesMessageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-editor': typeof AgentEditorRoute
  '/chat': typeof ChatRoute
  '/prompt-editor': typeof PromptEditorRoute
  '/use-gen': typeof UseGenRoute
  '/api/chat': typeof ApiChatRoute
  '/api/agent-editor/$chatId': typeof ApiAgentEditorChatIdRoute
  '/api/chats/$chatId': typeof ApiChatsChatIdRouteWithChildren
  '/api/chats/': typeof ApiChatsIndexRoute
  '/api/chats/$chatId/messages/$messageId': typeof ApiChatsChatIdMessagesMessageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-editor'
    | '/chat'
    | '/prompt-editor'
    | '/use-gen'
    | '/api/chat'
    | '/api/agent-editor/$chatId'
    | '/api/chats/$chatId'
    | '/api/chats/'
    | '/api/chats/$chatId/messages/$messageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-editor'
    | '/chat'
    | '/prompt-editor'
    | '/use-gen'
    | '/api/chat'
    | '/api/agent-editor/$chatId'
    | '/api/chats/$chatId'
    | '/api/chats'
    | '/api/chats/$chatId/messages/$messageId'
  id:
    | '__root__'
    | '/'
    | '/agent-editor'
    | '/chat'
    | '/prompt-editor'
    | '/use-gen'
    | '/api/chat'
    | '/api/agent-editor/$chatId'
    | '/api/chats/$chatId'
    | '/api/chats/'
    | '/api/chats/$chatId/messages/$messageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentEditorRoute: typeof AgentEditorRoute
  ChatRoute: typeof ChatRoute
  PromptEditorRoute: typeof PromptEditorRoute
  UseGenRoute: typeof UseGenRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiAgentEditorChatIdRoute: typeof ApiAgentEditorChatIdRoute
  ApiChatsChatIdRoute: typeof ApiChatsChatIdRouteWithChildren
  ApiChatsIndexRoute: typeof ApiChatsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/use-gen': {
      id: '/use-gen'
      path: '/use-gen'
      fullPath: '/use-gen'
      preLoaderRoute: typeof UseGenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-editor': {
      id: '/prompt-editor'
      path: '/prompt-editor'
      fullPath: '/prompt-editor'
      preLoaderRoute: typeof PromptEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-editor': {
      id: '/agent-editor'
      path: '/agent-editor'
      fullPath: '/agent-editor'
      preLoaderRoute: typeof AgentEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chats/': {
      id: '/api/chats/'
      path: '/api/chats'
      fullPath: '/api/chats/'
      preLoaderRoute: typeof ApiChatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chats/$chatId': {
      id: '/api/chats/$chatId'
      path: '/api/chats/$chatId'
      fullPath: '/api/chats/$chatId'
      preLoaderRoute: typeof ApiChatsChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-editor/$chatId': {
      id: '/api/agent-editor/$chatId'
      path: '/api/agent-editor/$chatId'
      fullPath: '/api/agent-editor/$chatId'
      preLoaderRoute: typeof ApiAgentEditorChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chats/$chatId/messages/$messageId': {
      id: '/api/chats/$chatId/messages/$messageId'
      path: '/messages/$messageId'
      fullPath: '/api/chats/$chatId/messages/$messageId'
      preLoaderRoute: typeof ApiChatsChatIdMessagesMessageIdRouteImport
      parentRoute: typeof ApiChatsChatIdRoute
    }
  }
}

interface ApiChatsChatIdRouteChildren {
  ApiChatsChatIdMessagesMessageIdRoute: typeof ApiChatsChatIdMessagesMessageIdRoute
}

const ApiChatsChatIdRouteChildren: ApiChatsChatIdRouteChildren = {
  ApiChatsChatIdMessagesMessageIdRoute: ApiChatsChatIdMessagesMessageIdRoute,
}

const ApiChatsChatIdRouteWithChildren = ApiChatsChatIdRoute._addFileChildren(
  ApiChatsChatIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentEditorRoute: AgentEditorRoute,
  ChatRoute: ChatRoute,
  PromptEditorRoute: PromptEditorRoute,
  UseGenRoute: UseGenRoute,
  ApiChatRoute: ApiChatRoute,
  ApiAgentEditorChatIdRoute: ApiAgentEditorChatIdRoute,
  ApiChatsChatIdRoute: ApiChatsChatIdRouteWithChildren,
  ApiChatsIndexRoute: ApiChatsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
