/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UseGenRouteImport } from './routes/use-gen'
import { Route as UseChatRouteImport } from './routes/use-chat'
import { Route as PromptEditorRouteImport } from './routes/prompt-editor'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AgentEditorRouteImport } from './routes/agent-editor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as AdvancedChatIndexRouteImport } from './routes/advanced-chat/index'
import { Route as ChatChatIdRouteImport } from './routes/chat/$chatId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdvancedChatChatIdRouteImport } from './routes/advanced-chat/$chatId'
import { Route as ChatAdvancedIndexRouteImport } from './routes/chat/advanced/index'
import { Route as ApiChatsIndexRouteImport } from './routes/api/chats/index'
import { Route as ApiAdvancedChatIndexRouteImport } from './routes/api/advanced-chat/index'
import { Route as ApiChatsChatIdRouteImport } from './routes/api/chats/$chatId'
import { Route as ApiAgentEditorChatIdRouteImport } from './routes/api/agent-editor/$chatId'
import { Route as ApiAdvancedChatChatIdRouteImport } from './routes/api/advanced-chat/$chatId'
import { Route as ApiAdvancedChatChatIdResumeRouteImport } from './routes/api/advanced-chat/$chatId.resume'
import { Route as ApiAdvancedChatChatIdCompletionRouteImport } from './routes/api/advanced-chat/$chatId.completion'
import { Route as ApiChatsChatIdRunsIndexRouteImport } from './routes/api/chats/$chatId/runs/index'
import { Route as ApiChatsChatIdMessagesMessageIdRouteImport } from './routes/api/chats/$chatId/messages/$messageId'
import { Route as ApiChatsChatIdRunsRunIdStreamRouteImport } from './routes/api/chats/$chatId/runs/$runId/stream'
import { Route as ApiChatsChatIdRunsRunIdCancelRouteImport } from './routes/api/chats/$chatId/runs/$runId/cancel'

const UseGenRoute = UseGenRouteImport.update({
  id: '/use-gen',
  path: '/use-gen',
  getParentRoute: () => rootRouteImport,
} as any)
const UseChatRoute = UseChatRouteImport.update({
  id: '/use-chat',
  path: '/use-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptEditorRoute = PromptEditorRouteImport.update({
  id: '/prompt-editor',
  path: '/prompt-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentEditorRoute = AgentEditorRouteImport.update({
  id: '/agent-editor',
  path: '/agent-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const AdvancedChatIndexRoute = AdvancedChatIndexRouteImport.update({
  id: '/advanced-chat/',
  path: '/advanced-chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => ChatRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedChatChatIdRoute = AdvancedChatChatIdRouteImport.update({
  id: '/advanced-chat/$chatId',
  path: '/advanced-chat/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatAdvancedIndexRoute = ChatAdvancedIndexRouteImport.update({
  id: '/advanced/',
  path: '/advanced/',
  getParentRoute: () => ChatRoute,
} as any)
const ApiChatsIndexRoute = ApiChatsIndexRouteImport.update({
  id: '/api/chats/',
  path: '/api/chats/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdvancedChatIndexRoute = ApiAdvancedChatIndexRouteImport.update({
  id: '/api/advanced-chat/',
  path: '/api/advanced-chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatsChatIdRoute = ApiChatsChatIdRouteImport.update({
  id: '/api/chats/$chatId',
  path: '/api/chats/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentEditorChatIdRoute = ApiAgentEditorChatIdRouteImport.update({
  id: '/api/agent-editor/$chatId',
  path: '/api/agent-editor/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdvancedChatChatIdRoute = ApiAdvancedChatChatIdRouteImport.update({
  id: '/api/advanced-chat/$chatId',
  path: '/api/advanced-chat/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdvancedChatChatIdResumeRoute =
  ApiAdvancedChatChatIdResumeRouteImport.update({
    id: '/resume',
    path: '/resume',
    getParentRoute: () => ApiAdvancedChatChatIdRoute,
  } as any)
const ApiAdvancedChatChatIdCompletionRoute =
  ApiAdvancedChatChatIdCompletionRouteImport.update({
    id: '/completion',
    path: '/completion',
    getParentRoute: () => ApiAdvancedChatChatIdRoute,
  } as any)
const ApiChatsChatIdRunsIndexRoute = ApiChatsChatIdRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => ApiChatsChatIdRoute,
} as any)
const ApiChatsChatIdMessagesMessageIdRoute =
  ApiChatsChatIdMessagesMessageIdRouteImport.update({
    id: '/messages/$messageId',
    path: '/messages/$messageId',
    getParentRoute: () => ApiChatsChatIdRoute,
  } as any)
const ApiChatsChatIdRunsRunIdStreamRoute =
  ApiChatsChatIdRunsRunIdStreamRouteImport.update({
    id: '/runs/$runId/stream',
    path: '/runs/$runId/stream',
    getParentRoute: () => ApiChatsChatIdRoute,
  } as any)
const ApiChatsChatIdRunsRunIdCancelRoute =
  ApiChatsChatIdRunsRunIdCancelRouteImport.update({
    id: '/runs/$runId/cancel',
    path: '/runs/$runId/cancel',
    getParentRoute: () => ApiChatsChatIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-editor': typeof AgentEditorRoute
  '/chat': typeof ChatRouteWithChildren
  '/prompt-editor': typeof PromptEditorRoute
  '/use-chat': typeof UseChatRoute
  '/use-gen': typeof UseGenRoute
  '/advanced-chat/$chatId': typeof AdvancedChatChatIdRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/advanced-chat/': typeof AdvancedChatIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/api/advanced-chat/$chatId': typeof ApiAdvancedChatChatIdRouteWithChildren
  '/api/agent-editor/$chatId': typeof ApiAgentEditorChatIdRoute
  '/api/chats/$chatId': typeof ApiChatsChatIdRouteWithChildren
  '/api/advanced-chat/': typeof ApiAdvancedChatIndexRoute
  '/api/chats/': typeof ApiChatsIndexRoute
  '/chat/advanced/': typeof ChatAdvancedIndexRoute
  '/api/advanced-chat/$chatId/completion': typeof ApiAdvancedChatChatIdCompletionRoute
  '/api/advanced-chat/$chatId/resume': typeof ApiAdvancedChatChatIdResumeRoute
  '/api/chats/$chatId/messages/$messageId': typeof ApiChatsChatIdMessagesMessageIdRoute
  '/api/chats/$chatId/runs/': typeof ApiChatsChatIdRunsIndexRoute
  '/api/chats/$chatId/runs/$runId/cancel': typeof ApiChatsChatIdRunsRunIdCancelRoute
  '/api/chats/$chatId/runs/$runId/stream': typeof ApiChatsChatIdRunsRunIdStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-editor': typeof AgentEditorRoute
  '/prompt-editor': typeof PromptEditorRoute
  '/use-chat': typeof UseChatRoute
  '/use-gen': typeof UseGenRoute
  '/advanced-chat/$chatId': typeof AdvancedChatChatIdRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/advanced-chat': typeof AdvancedChatIndexRoute
  '/chat': typeof ChatIndexRoute
  '/api/advanced-chat/$chatId': typeof ApiAdvancedChatChatIdRouteWithChildren
  '/api/agent-editor/$chatId': typeof ApiAgentEditorChatIdRoute
  '/api/chats/$chatId': typeof ApiChatsChatIdRouteWithChildren
  '/api/advanced-chat': typeof ApiAdvancedChatIndexRoute
  '/api/chats': typeof ApiChatsIndexRoute
  '/chat/advanced': typeof ChatAdvancedIndexRoute
  '/api/advanced-chat/$chatId/completion': typeof ApiAdvancedChatChatIdCompletionRoute
  '/api/advanced-chat/$chatId/resume': typeof ApiAdvancedChatChatIdResumeRoute
  '/api/chats/$chatId/messages/$messageId': typeof ApiChatsChatIdMessagesMessageIdRoute
  '/api/chats/$chatId/runs': typeof ApiChatsChatIdRunsIndexRoute
  '/api/chats/$chatId/runs/$runId/cancel': typeof ApiChatsChatIdRunsRunIdCancelRoute
  '/api/chats/$chatId/runs/$runId/stream': typeof ApiChatsChatIdRunsRunIdStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-editor': typeof AgentEditorRoute
  '/chat': typeof ChatRouteWithChildren
  '/prompt-editor': typeof PromptEditorRoute
  '/use-chat': typeof UseChatRoute
  '/use-gen': typeof UseGenRoute
  '/advanced-chat/$chatId': typeof AdvancedChatChatIdRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/advanced-chat/': typeof AdvancedChatIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/api/advanced-chat/$chatId': typeof ApiAdvancedChatChatIdRouteWithChildren
  '/api/agent-editor/$chatId': typeof ApiAgentEditorChatIdRoute
  '/api/chats/$chatId': typeof ApiChatsChatIdRouteWithChildren
  '/api/advanced-chat/': typeof ApiAdvancedChatIndexRoute
  '/api/chats/': typeof ApiChatsIndexRoute
  '/chat/advanced/': typeof ChatAdvancedIndexRoute
  '/api/advanced-chat/$chatId/completion': typeof ApiAdvancedChatChatIdCompletionRoute
  '/api/advanced-chat/$chatId/resume': typeof ApiAdvancedChatChatIdResumeRoute
  '/api/chats/$chatId/messages/$messageId': typeof ApiChatsChatIdMessagesMessageIdRoute
  '/api/chats/$chatId/runs/': typeof ApiChatsChatIdRunsIndexRoute
  '/api/chats/$chatId/runs/$runId/cancel': typeof ApiChatsChatIdRunsRunIdCancelRoute
  '/api/chats/$chatId/runs/$runId/stream': typeof ApiChatsChatIdRunsRunIdStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-editor'
    | '/chat'
    | '/prompt-editor'
    | '/use-chat'
    | '/use-gen'
    | '/advanced-chat/$chatId'
    | '/api/chat'
    | '/chat/$chatId'
    | '/advanced-chat/'
    | '/chat/'
    | '/api/advanced-chat/$chatId'
    | '/api/agent-editor/$chatId'
    | '/api/chats/$chatId'
    | '/api/advanced-chat/'
    | '/api/chats/'
    | '/chat/advanced/'
    | '/api/advanced-chat/$chatId/completion'
    | '/api/advanced-chat/$chatId/resume'
    | '/api/chats/$chatId/messages/$messageId'
    | '/api/chats/$chatId/runs/'
    | '/api/chats/$chatId/runs/$runId/cancel'
    | '/api/chats/$chatId/runs/$runId/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-editor'
    | '/prompt-editor'
    | '/use-chat'
    | '/use-gen'
    | '/advanced-chat/$chatId'
    | '/api/chat'
    | '/chat/$chatId'
    | '/advanced-chat'
    | '/chat'
    | '/api/advanced-chat/$chatId'
    | '/api/agent-editor/$chatId'
    | '/api/chats/$chatId'
    | '/api/advanced-chat'
    | '/api/chats'
    | '/chat/advanced'
    | '/api/advanced-chat/$chatId/completion'
    | '/api/advanced-chat/$chatId/resume'
    | '/api/chats/$chatId/messages/$messageId'
    | '/api/chats/$chatId/runs'
    | '/api/chats/$chatId/runs/$runId/cancel'
    | '/api/chats/$chatId/runs/$runId/stream'
  id:
    | '__root__'
    | '/'
    | '/agent-editor'
    | '/chat'
    | '/prompt-editor'
    | '/use-chat'
    | '/use-gen'
    | '/advanced-chat/$chatId'
    | '/api/chat'
    | '/chat/$chatId'
    | '/advanced-chat/'
    | '/chat/'
    | '/api/advanced-chat/$chatId'
    | '/api/agent-editor/$chatId'
    | '/api/chats/$chatId'
    | '/api/advanced-chat/'
    | '/api/chats/'
    | '/chat/advanced/'
    | '/api/advanced-chat/$chatId/completion'
    | '/api/advanced-chat/$chatId/resume'
    | '/api/chats/$chatId/messages/$messageId'
    | '/api/chats/$chatId/runs/'
    | '/api/chats/$chatId/runs/$runId/cancel'
    | '/api/chats/$chatId/runs/$runId/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentEditorRoute: typeof AgentEditorRoute
  ChatRoute: typeof ChatRouteWithChildren
  PromptEditorRoute: typeof PromptEditorRoute
  UseChatRoute: typeof UseChatRoute
  UseGenRoute: typeof UseGenRoute
  AdvancedChatChatIdRoute: typeof AdvancedChatChatIdRoute
  ApiChatRoute: typeof ApiChatRoute
  AdvancedChatIndexRoute: typeof AdvancedChatIndexRoute
  ApiAdvancedChatChatIdRoute: typeof ApiAdvancedChatChatIdRouteWithChildren
  ApiAgentEditorChatIdRoute: typeof ApiAgentEditorChatIdRoute
  ApiChatsChatIdRoute: typeof ApiChatsChatIdRouteWithChildren
  ApiAdvancedChatIndexRoute: typeof ApiAdvancedChatIndexRoute
  ApiChatsIndexRoute: typeof ApiChatsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/use-gen': {
      id: '/use-gen'
      path: '/use-gen'
      fullPath: '/use-gen'
      preLoaderRoute: typeof UseGenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-chat': {
      id: '/use-chat'
      path: '/use-chat'
      fullPath: '/use-chat'
      preLoaderRoute: typeof UseChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-editor': {
      id: '/prompt-editor'
      path: '/prompt-editor'
      fullPath: '/prompt-editor'
      preLoaderRoute: typeof PromptEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-editor': {
      id: '/agent-editor'
      path: '/agent-editor'
      fullPath: '/agent-editor'
      preLoaderRoute: typeof AgentEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/advanced-chat/': {
      id: '/advanced-chat/'
      path: '/advanced-chat'
      fullPath: '/advanced-chat/'
      preLoaderRoute: typeof AdvancedChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$chatId': {
      id: '/chat/$chatId'
      path: '/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced-chat/$chatId': {
      id: '/advanced-chat/$chatId'
      path: '/advanced-chat/$chatId'
      fullPath: '/advanced-chat/$chatId'
      preLoaderRoute: typeof AdvancedChatChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/advanced/': {
      id: '/chat/advanced/'
      path: '/advanced'
      fullPath: '/chat/advanced/'
      preLoaderRoute: typeof ChatAdvancedIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/api/chats/': {
      id: '/api/chats/'
      path: '/api/chats'
      fullPath: '/api/chats/'
      preLoaderRoute: typeof ApiChatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/advanced-chat/': {
      id: '/api/advanced-chat/'
      path: '/api/advanced-chat'
      fullPath: '/api/advanced-chat/'
      preLoaderRoute: typeof ApiAdvancedChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chats/$chatId': {
      id: '/api/chats/$chatId'
      path: '/api/chats/$chatId'
      fullPath: '/api/chats/$chatId'
      preLoaderRoute: typeof ApiChatsChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-editor/$chatId': {
      id: '/api/agent-editor/$chatId'
      path: '/api/agent-editor/$chatId'
      fullPath: '/api/agent-editor/$chatId'
      preLoaderRoute: typeof ApiAgentEditorChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/advanced-chat/$chatId': {
      id: '/api/advanced-chat/$chatId'
      path: '/api/advanced-chat/$chatId'
      fullPath: '/api/advanced-chat/$chatId'
      preLoaderRoute: typeof ApiAdvancedChatChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/advanced-chat/$chatId/resume': {
      id: '/api/advanced-chat/$chatId/resume'
      path: '/resume'
      fullPath: '/api/advanced-chat/$chatId/resume'
      preLoaderRoute: typeof ApiAdvancedChatChatIdResumeRouteImport
      parentRoute: typeof ApiAdvancedChatChatIdRoute
    }
    '/api/advanced-chat/$chatId/completion': {
      id: '/api/advanced-chat/$chatId/completion'
      path: '/completion'
      fullPath: '/api/advanced-chat/$chatId/completion'
      preLoaderRoute: typeof ApiAdvancedChatChatIdCompletionRouteImport
      parentRoute: typeof ApiAdvancedChatChatIdRoute
    }
    '/api/chats/$chatId/runs/': {
      id: '/api/chats/$chatId/runs/'
      path: '/runs'
      fullPath: '/api/chats/$chatId/runs/'
      preLoaderRoute: typeof ApiChatsChatIdRunsIndexRouteImport
      parentRoute: typeof ApiChatsChatIdRoute
    }
    '/api/chats/$chatId/messages/$messageId': {
      id: '/api/chats/$chatId/messages/$messageId'
      path: '/messages/$messageId'
      fullPath: '/api/chats/$chatId/messages/$messageId'
      preLoaderRoute: typeof ApiChatsChatIdMessagesMessageIdRouteImport
      parentRoute: typeof ApiChatsChatIdRoute
    }
    '/api/chats/$chatId/runs/$runId/stream': {
      id: '/api/chats/$chatId/runs/$runId/stream'
      path: '/runs/$runId/stream'
      fullPath: '/api/chats/$chatId/runs/$runId/stream'
      preLoaderRoute: typeof ApiChatsChatIdRunsRunIdStreamRouteImport
      parentRoute: typeof ApiChatsChatIdRoute
    }
    '/api/chats/$chatId/runs/$runId/cancel': {
      id: '/api/chats/$chatId/runs/$runId/cancel'
      path: '/runs/$runId/cancel'
      fullPath: '/api/chats/$chatId/runs/$runId/cancel'
      preLoaderRoute: typeof ApiChatsChatIdRunsRunIdCancelRouteImport
      parentRoute: typeof ApiChatsChatIdRoute
    }
  }
}

interface ChatRouteChildren {
  ChatChatIdRoute: typeof ChatChatIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ChatAdvancedIndexRoute: typeof ChatAdvancedIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatChatIdRoute: ChatChatIdRoute,
  ChatIndexRoute: ChatIndexRoute,
  ChatAdvancedIndexRoute: ChatAdvancedIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface ApiAdvancedChatChatIdRouteChildren {
  ApiAdvancedChatChatIdCompletionRoute: typeof ApiAdvancedChatChatIdCompletionRoute
  ApiAdvancedChatChatIdResumeRoute: typeof ApiAdvancedChatChatIdResumeRoute
}

const ApiAdvancedChatChatIdRouteChildren: ApiAdvancedChatChatIdRouteChildren = {
  ApiAdvancedChatChatIdCompletionRoute: ApiAdvancedChatChatIdCompletionRoute,
  ApiAdvancedChatChatIdResumeRoute: ApiAdvancedChatChatIdResumeRoute,
}

const ApiAdvancedChatChatIdRouteWithChildren =
  ApiAdvancedChatChatIdRoute._addFileChildren(
    ApiAdvancedChatChatIdRouteChildren,
  )

interface ApiChatsChatIdRouteChildren {
  ApiChatsChatIdMessagesMessageIdRoute: typeof ApiChatsChatIdMessagesMessageIdRoute
  ApiChatsChatIdRunsIndexRoute: typeof ApiChatsChatIdRunsIndexRoute
  ApiChatsChatIdRunsRunIdCancelRoute: typeof ApiChatsChatIdRunsRunIdCancelRoute
  ApiChatsChatIdRunsRunIdStreamRoute: typeof ApiChatsChatIdRunsRunIdStreamRoute
}

const ApiChatsChatIdRouteChildren: ApiChatsChatIdRouteChildren = {
  ApiChatsChatIdMessagesMessageIdRoute: ApiChatsChatIdMessagesMessageIdRoute,
  ApiChatsChatIdRunsIndexRoute: ApiChatsChatIdRunsIndexRoute,
  ApiChatsChatIdRunsRunIdCancelRoute: ApiChatsChatIdRunsRunIdCancelRoute,
  ApiChatsChatIdRunsRunIdStreamRoute: ApiChatsChatIdRunsRunIdStreamRoute,
}

const ApiChatsChatIdRouteWithChildren = ApiChatsChatIdRoute._addFileChildren(
  ApiChatsChatIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentEditorRoute: AgentEditorRoute,
  ChatRoute: ChatRouteWithChildren,
  PromptEditorRoute: PromptEditorRoute,
  UseChatRoute: UseChatRoute,
  UseGenRoute: UseGenRoute,
  AdvancedChatChatIdRoute: AdvancedChatChatIdRoute,
  ApiChatRoute: ApiChatRoute,
  AdvancedChatIndexRoute: AdvancedChatIndexRoute,
  ApiAdvancedChatChatIdRoute: ApiAdvancedChatChatIdRouteWithChildren,
  ApiAgentEditorChatIdRoute: ApiAgentEditorChatIdRoute,
  ApiChatsChatIdRoute: ApiChatsChatIdRouteWithChildren,
  ApiAdvancedChatIndexRoute: ApiAdvancedChatIndexRoute,
  ApiChatsIndexRoute: ApiChatsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
